name: FunEffects
version: 1.1.5
author: heyimblake
main: me.heyimblake.FunEffects.Main
website: http://funeffects.heyimblake.me
database: false
commands:
  giveenderpurr:
    description: Gives 16 EnderPurrs.
    usage: /<command> (player)
    aliases: gep
    permission: funeffects.giveender
    permission-message: ยง4Insufficient Permissions.
  givefireball:
    description: Gives 16 FireBalls.
    usage: /<command> (player)
    aliases: gfb
    permission: funeffects.givefireball
    permission-message: ยง4Insufficient Permissions.
permissions:
   funeffects.*:
     description: Gives access to all FunEffects commands
     children:
       funeffects.giveender: true
       funeffects.givefireball: true
     default: op